openapi: 3.0.0

info:
  title: SAML Jackson API
  description: SAML service
  version: 1.0.0
  contact:
    name: "Boxy HQ"
    url: "https://boxyhq.com/"
    email: "deepak@boxyhq.com"
  license:
    name: "<license>"
    url: "https://boxyhq.com/license"

servers:
  - url: https://boxyhq.com/api/v1/
    description: Production server

paths:
  /saml/config:
    $ref: './paths/create-config.yml'