openapi: 3.0.0

info:
  title: SAML Jackson API
  description: This is the API documentation for SAML Jackson service.
  termsOfService: https://boxyhq.com/terms.html
  version: 0.3.3
  contact:
    name: Boxy HQ
    url: https://boxyhq.com/
    email: deepak@boxyhq.com
  license:
    name: Apache-2.0 License
    url: https://github.com/boxyhq/jackson/blob/main/LICENSE

servers:
  - url: http://localhost:5000/
    description: Development server

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: Authorization
      description: 'Authorization: Api-Key your-api-key'
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Access token
security:
  - apiKey: []
  - bearerAuth: []

paths:
  $ref: ./paths/index.yml