openapi: 3.0.0

info:
  title: SAML Jackson API
  description: This is the API documentation SAML Jackson service.
  termsOfService: https://boxyhq.com/terms.html
  version: 1.0.0
  contact:
    name: Boxy HQ
    url: https://boxyhq.com/
    email: deepak@boxyhq.com
  license:
    name: Apache-2.0 License
    url: https://github.com/boxyhq/jackson/blob/main/LICENSE

servers:
  - url: https://boxyhq.com/
    description: Production server

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Api-Key

security:
  - ApiKeyAuth: []

paths:
  $ref: ./paths/index.yml