---
bases:
  - ../../base
  - ../../base/services

resources:
  - ./secrets.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Service
      name: jackson
    path: jackson-service.yaml

commonLabels:
  jacksondev: '1'

images:
  - name: boxyhq/jackson
    newTag: 1.12.0
