apiVersion: v1
kind: Service
metadata:
  name: jackson
  namespace: '{{repl ConfigOption "namespace"}}'
  labels:
    app: jackson
    tier: jackson
spec:
  type: LoadBalancer
  selector:
    app: jackson
    tier: jackson
