summary: Create SAML configuration
operationId: create-saml-config
tags:
  - SAML Config
consumes:
  - application/x-www-form-urlencoded
parameters:
  - name: encodedRawMetadata
    in: formData
    type: string
    required: true
    description: Base64 encoding of the XML metadata
  - name: defaultRedirectUrl
    in: formData
    type: string
    required: true
    description: The redirect URL to use in the IdP login flow
  - name: redirectUrl
    in: formData
    type: string
    required: true
    description: JSON encoded array containing a list of allowed redirect URLs
  - name: tenant
    in: formData
    type: string
    required: true
    description: Tenant
  - name: product
    in: formData
    type: string
    required: true
    description: Product
responses:
  '200':
    description: Success
    schema:
      type: object
      properties:
        client_id:
          type: string
        client_secret:
          type: string
        provider:
          type: string
      example:
        client_id: 8958e13053832b5af58fdf2ee83f35f5d013dc74
        client_secret: 13f01f4df5b01770c616e682d14d3ba23f20948cfa89b1d7
        type: accounts.google.com
  '401':
    description: Unauthorized