summary: Delete SAML configuration
operationId: delete-saml-config
tags:
  - SAML Config
consumes:
  - application/x-www-form-urlencoded
parameters:
  - name: clientID
    in: formData
    type: string
    required: true
    description: Client ID
  - name: clientSecret
    in: formData
    type: string
    required: true
    description: Client Secret
  - name: tenant
    in: formData
    type: string
    required: true
    description: Tenant
  - name: product
    in: formData
    type: string
    required: true
    description: Product
responses:
  '200':
    description: Success
  '401':
    description: Unauthorized

