summary: Get SAML configuration
operationId: getConfig
tags:
  - SAML Config
parameters:
  - in: query
    name: tenant
    type: string
    description: Tenant
  - in: query
    name: product
    type: string
    description: Product
  - in: query
    name: clientID
    type: string
    description: Client ID
responses:
  '200':
    description: Success
    schema:
      type: object
      properties:
        provider:
          type: string
      example:
        type: accounts.google.com
  '401':
    description: Unauthorized

