apiVersion: v1
kind: Service
metadata:
  name: jackson
  labels:
    app: jackson
    tier: jackson
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5225
      targetPort: 5225
  selector:
    app: jackson
    tier: jackson
