---
bases:
  - ../../base
  - ../../base/services
  - ../dbs/mariadb

resources:
  - ./secrets.yaml

patches:
  - ./jackson-service.yaml

commonLabels:
  jacksondev: '1'

images:
  - name: boxyhq/jackson
    newTag: 1.9.7
