# This is a basic workflow to help you get started with Actions

name: Next JS Project SBOM SPDX
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Next Js Project Scan
        uses: anchore/scan-action@v3
        with:
          path: "./"
          fail-build: false
      - name: Next Js Project SBOM Report [SPDX]
        uses: anchore/sbom-action@v0
        with:
          format: spdx
          artifact-name: sbom.spdx
      - name: Publish report [SPDX]
        uses: anchore/sbom-action/publish-sbom@v0
        with:
          sbom-artifact-match: ".*\\.spdx$"
      - name: Next Js Project SBOM Report [CycloneDx]
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx
          artifact-name: sbom.cyclonedx
      - name: Publish report [CycloneDx]
        uses: anchore/sbom-action/publish-sbom@v0
        with:
          sbom-artifact-match: ".*\\.cyclonedx$"
      - name: Remove older SBOMs
        run: rm -rf sbom*.* || true
      - name: Download artifact for SPDX Report
        uses: actions/download-artifact@v2
        with:
          name: sbom.spdx
      - name: Download artifact for CycloneDx Report
        uses: actions/download-artifact@v2
        with:
          name: sbom.cyclonedx
      - name: Build the container image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest
      - name: Scan docker image using TERN
        uses: philips-labs/tern-action@v1.1.0
        id: scan
        with:
          image: localbuild/testimage:latest
          format: spdxtagvalue
          output: docker_sbom.spdx
      - name: Create/Clear folder
        run: mkdir -p ./_docker/ && rm -rf ./_docker/*.* || true
      - name: Docker CycloneDx report
        run: npm install -g @appthreat/cdxgen && cdxgen localbuild/testimage:latest -o ./_docker/sbom.xml -t docker
      - name: Move Report
        run: mv docker_sbom.spdx "./_docker/sbom.spdx"
      - name: Commit report
        run: |
          rm results.sarif
          git pull
          git config --global user.email "ukrocks.mehta@gmail.com"
          git config --global user.name "Utkarsh Mehta"
          git add . && git commit -am "Automated report" && git push || true
