# This is a basic workflow to help you get started with Actions

name: Container Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: NPM Package Scan
        uses: anchore/scan-action@v3
        with:
          path: "./npm"
          fail-build: false
      - name: Set output variables
        id: vars
        run: |
          publishTag="latest"
          PACKAGE_VERSION=$(cat package.json \
          | grep version \
          | head -1 \
          | awk -F: '{ print $2 }' \
          | sed 's/[",]//g')
          if [[ "$GITHUB_REF" == *\/release ]]
          then
            publishTag="latest"
            echo ::set-output name=filename::"${PACKAGE_VERSION}-latest"
          else
            publishTag="beta"
            echo ::set-output name=filename::"${PACKAGE_VERSION}-beta.${GITHUB_RUN_NUMBER}"
          fi"
      - name: NPM Pacakge SBOM Report [SPDX]
        uses: anchore/sbom-action@v0
        with:
          format: spdx
          artifact-name: ${{ steps.vars.outputs.filename }}.spdx
      - name: Publish report [SPDX]
        uses: anchore/sbom-action/publish-sbom@v0
        with:
          sbom-artifact-match: ".*\\.spdx$"
      - name: NPM Pacakge SBOM Report [CycloneDx]
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx
          artifact-name: ${{ steps.vars.outputs.filename }}.cyclonedx
      - name: Publish report [CycloneDx]
        uses: anchore/sbom-action/publish-sbom@v0
        with:
          sbom-artifact-match: ".*\\.cyclonedx$"
