name: Publish React component SDK to npmjs
on:
  workflow_call:
    inputs:
      npmversion:
        required: true
        type: string
      publishtag:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./sdk/ui/react

    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - name: Publish NPM
        # if: github.ref == 'refs/heads/release' || contains(github.ref, 'refs/tags/beta-v')
        run: |
          npm install -g json
          PKG_VERSION=${{ inputs.npmversion }}
          json -I -f package.json -e "this.version=\"${PKG_VERSION}\""

          npm publish --tag ${{ inputs.publishtag }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
