name: Publish React component SDK to npmjs
on:
  push:
    branches:
      - '702-react-sdk-login'
  # release:
  #   types: [created]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./sdk/ui/react

    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
