name: Build Images and Handle Uffizzi Previews.

on:
  pull_request:
    types: [closed]

jobs:
  delete-uffizzi-preview:
    name: Use Remote Workflow to Delete an Existing Preview
    uses: UffizziCloud/preview-action/.github/workflows/reusable.yaml@v2.1.0
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    with:
      compose-file-cache-key: ''
      compose-file-cache-path: docker-compose.rendered.yml
      username: deepak@boxyhq.com
      server: https://app.uffizzi.com
      project: saml-jackson-hje1
    secrets:
      password: ${{ secrets.UFFIZZI_PASSWORD }}
    permissions:
      contents: read
      pull-requests: write

  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          # NOTE: at now only orgs is supported
          owner: ${{ github.repository_owner }}
          name: jackson-dev
          # NOTE: using Personal Access Token
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: pr-${{github.event.pull_request.number}}
